import re

with open('.gemini/antigravity-ide/brain/4dc9b9e6-25a6-44b2-a4d3-bb6e765b49e1/scratch/DocDetail.jsx.bak', 'r') as f:
    lines = f.readlines()

for i, line in enumerate(lines):
    if '{/* --- Edit Document Modal --- */}' in line:
        start = i
        break

# The file goes until line 1445 or so (return of DocDetail)
# We can just extract everything from `start` to the end of the return block.
with open('ToolCalendar.Api/ClientApp/src/documents/pages/DocDetail/components/DocModals.jsx', 'w') as f:
    f.write('import React, { useState } from "react";\n')
    f.write('import { X, Save, Loader2, Paperclip } from "lucide-react";\n')
    f.write('import { cn } from "@/lib/utils";\n')
    f.write('import { toast } from "react-hot-toast";\n')
    f.write('import ConfirmationModal from "@/components/ConfirmationModal";\n\n')
    f.write('export function DocModals({ \n')
    f.write('  docId, doc, setDoc, \n')
    f.write('  isEditModalOpen, setIsEditModalOpen, editForm, setEditForm, departments, users,\n')
    f.write('  isDeleteModalOpen, setIsDeleteModalOpen, executeDelete,\n')
    f.write('  isEvidenceModalOpen, setIsEvidenceModalOpen, fetchData,\n')
    f.write('  previewImage, setPreviewImage,\n')
    f.write('  isFullscreenPdf, setIsFullscreenPdf, pdfUrl\n')
    f.write('}) {\n')
    f.write('  const [isSaving, setIsSaving] = useState(false);\n')
    f.write('  const [evidenceNote, setEvidenceNote] = useState("");\n')
    f.write('  const [evidenceFiles, setEvidenceFiles] = useState([]);\n\n')
    f.write('  const handleEditChange = (field, value) => { setEditForm({ ...editForm, [field]: value }); };\n')
    f.write('  const handleSaveEdit = async () => {\n')
    f.write('    setIsSaving(true)\n')
    f.write('    try {\n')
    f.write('      const response = await fetch(`/api/documents/${docId}`, {\n')
    f.write('        method: "PUT",\n')
    f.write('        headers: { Authorization: `Bearer ${localStorage.getItem("auth_token")}`, "Content-Type": "application/json" },\n')
    f.write('        body: JSON.stringify(editForm),\n')
    f.write('      })\n')
    f.write('      if (response.ok) { setDoc(editForm); setIsEditModalOpen(false); toast.success("Cập nhật văn bản thành công"); }\n')
    f.write('      else { toast.error("Có lỗi xảy ra khi lưu"); }\n')
    f.write('    } catch (error) {\n')
    f.write('      toast.error("Lỗi kết nối máy chủ");\n')
    f.write('    } finally { setIsSaving(false); }\n')
    f.write('  };\n\n')
    f.write('  const handleSubmitEvidence = async () => {\n')
    f.write('    setIsSaving(true)\n')
    f.write('    try {\n')
    f.write('      const formData = new FormData()\n')
    f.write('      formData.append("note", evidenceNote)\n')
    f.write('      evidenceFiles.forEach((file) => formData.append("files", file))\n')
    f.write('      const response = await fetch(`/api/documents/${docId}/evidence`, {\n')
    f.write('        method: "POST",\n')
    f.write('        headers: { Authorization: `Bearer ${localStorage.getItem("auth_token")}` },\n')
    f.write('        body: formData,\n')
    f.write('      })\n')
    f.write('      if (response.ok) {\n')
    f.write('        toast.success("Đã nộp kết quả xử lý thành công")\n')
    f.write('        setIsEvidenceModalOpen(false)\n')
    f.write('        fetchData()\n')
    f.write('      } else { toast.error("Có lỗi xảy ra khi lưu"); }\n')
    f.write('    } catch (error) {\n')
    f.write('      toast.error("Lỗi kết nối máy chủ");\n')
    f.write('    } finally { setIsSaving(false); }\n')
    f.write('  };\n\n')
    f.write('  return (\n')
    f.write('    <>\n')
    for line in lines[start:1445]:
        if 'ForwardDocumentModal' in line or 'parentRoutingId' in line or 'onForwardSuccess' in line or 'fetchRoutings()' in line or 'fetchData()' in line or '/>' in line and 'isForwardModalOpen' in ''.join(lines[start:1445]):
            # This is risky, let's just write everything and clean it up manually
            f.write(line)
    f.write('    </>\n')
    f.write('  );\n')
    f.write('}\n\n')
    f.write('const FormField = ({ label, value, onChange, icon: Icon, type = "text" }) => (\n')
    f.write('  <div className="flex flex-col gap-1.5">\n')
    f.write('    <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider ml-1">{label}</label>\n')
    f.write('    <div className="relative group">\n')
    f.write('      {Icon && <div className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-300 group-focus-within:text-red-500 transition-colors"><Icon size={16} strokeWidth={2.5} /></div>}\n')
    f.write('      {type === "textarea" ? (\n')
    f.write('        <textarea value={value || ""} onChange={(e) => onChange(e.target.value)} rows={4} className="w-full px-4 py-3 rounded-2xl bg-slate-50 border border-slate-100 text-xs font-bold text-slate-700 outline-none focus:border-red-300 focus:ring-4 focus:ring-red-50 transition-all leading-relaxed resize-none" />\n')
    f.write('      ) : (\n')
    f.write('        <input type={type} value={value || ""} onChange={(e) => onChange(e.target.value)} className={cn("w-full py-3 rounded-xl bg-slate-50 border border-slate-100 text-xs font-bold text-slate-700 outline-none focus:border-red-300 focus:ring-4 focus:ring-red-50 transition-all", Icon ? "pl-12 pr-4" : "px-4")} />\n')
    f.write('      )}\n')
    f.write('    </div>\n')
    f.write('  </div>\n')
    f.write(');\n')

